### PR TITLE
Added ability to import a barcode from a local image

### PR DESCRIPTION
**Pull request by franga2000**
As discussed in #51 

Status:

- [x] Functional implementation
- [ ] Tests
- [ ] Tyding up

### CODE REVIEW

**Comment by TheLastProject** [comment]
Could you please consider allowing me to edit this pull request so I can help complete this feature for the next release?

https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork :)

**Comment by franga2000** [comment]
Of course! It looks like that's already turned on, but I'll try explicitly giving you permission for my fork as well.

And sorry I left this unfinished again, stuff that pays the bills got in the way again 😢

**Comment by TheLastProject** [comment]
```
~/Projects/Catima(feature/import-local-image) » git push
ERROR: Permission to franga2000/loyalty-card-locker.git denied to TheLastProject.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Hmm, it's still not happy. But I guess I could create a new PR based on this to try to finish it myself. No worries about leaving it unfinished and thank you for telling me what happened. Life gets in the way, yeah :)

**Comment by franga2000** [comment]
I hadn't managed to actually do that until now, since I wasn't at a computer and the menu wasn't showing up on mobile. Try now

**Comment by TheLastProject** [comment]
Well, I've never seen GitHub fail this badly. For some reason this PR just isn't updating at all...

**Comment by TheLastProject** [comment]
I'm continuing this in #173 because wow, GitHub bugged out lol.

**Pull request closed without merging**
