### PR TITLE
Fix for the "Store" thumbnail position

### PR DESCRIPTION
**Pull request by SamantazFox**
That *may* fix the "Store" thumbnail position

NEEDS TESTING!!!

### CODE REVIEW

**Comment by TheLastProject** [comment]
I'm sorry, but it doesn't really feel like an improvement to me :(

image

**Comment by SamantazFox** [comment]
Ah, yeah, It's not really what I wanted.

5 AM commits are generally not a good idea. I will work more on that this weekend ^^

**Comment by SamantazFox** [comment]
I'm still trying to get The App to compile in here. It *will* take more time than expected :/

**Comment by TheLastProject** [comment]
No worries, thanks for the heads up.

**Comment by SamantazFox** [comment]
Sorry for closing, but running a proper version of the Android SDK on debian is a nightmare :/

**Comment by TheLastProject** [comment]
I totally understand, I ended up giving up and just running Android Studio too. It is definitely a problem with regards to Android, yeah.

**Pull request closed without merging**
