### PR TITLE
635 android 5 stuck row height, 619 star icon color

### PR DESCRIPTION
**Pull request by Kethen**
please review, for #635 and #619

https://user-images.githubusercontent.com/22017945/145800150-b3afa43e-de80-4172-bbdd-5d06af6276d1.mp4

### CODE REVIEW

**Comment by Altonss** [comment]
See the issue #681 for potential regressions I detetected

**Comment by OmlineEditor** [comment]
Use a completely white background. nothing is visible on a white background

**Comment by TheLastProject** [comment]
Please leave comments in issues, not a merged pull request. There's no way to keep track of the state of something in an already merged pull request.

**Pull request merged**
