### PR TITLE
Feature/groups

### PR DESCRIPTION
**Pull request by TheLastProject**
Group management:
- [x] Create groups
- [x] Rename groups
- [x] Delete groups

Card management:
- [x] View groups (in edit view)
- [x] Edit groups

Import/export
- [x] Import/export groups with cards

Filtering:
- [x] Group filtering

Unit testing:
- [x] Create group
- [x] Rename group
- [x] Delete group
- [x] View groups of card
- [x] Edit groups of card
- [x] Group filtering
- [x] Hiding of group options if no groups exist
- [x] Import/export

### CODE REVIEW

**Comment by TheLastProject** [comment]
This seems done now. I've been looking at your code all the time @arshbeerSingh, feel free to look at my code and tell me if you have any opinion (this feature took much longer to make than I expected so I've probably made some mistakes I can no longer properly see) :)

**Comment by arshbeerSingh** [comment]
@TheLastProject thank you very much for giving me the opportunity to review your code.
I will go through your code and would provide suggestions (if any) that I think would be helpful

**Comment by TheLastProject** [comment]
@arshbeerSingh Don't get me wrong with me merging this, you are still welcome to review, but I'd like to give translators a chance to translate and then get this out in a beta release :)

**Comment by arshbeerSingh** [comment]
@TheLastProject I understand. Sorry, I was not able to review your code or fix the assigned issues in the past few days as I was preparing for my school exams.

**Comment by TheLastProject** [comment]
Exams are more important! Good luck with them!

**Comment by arshbeerSingh** [comment]
Thank You very much @TheLastProject

**Pull request merged**
