### PR TITLE
Fix Issue #65

### PR DESCRIPTION
**Pull request by arshbeerSingh**

### CODE REVIEW

**Comment by TheLastProject** [comment]
I quickly installed this during my lunch break and I do want to ask for a few changes:

1. Ability to select multiple cards (it would be nice to already implement sharing multiple cards at once, but that could also be put in a separate PR/issue. The copy and edit icons will obviously only be shown when only a single card is selected). It should just display the number of selected cards like in WhatsApp or Telegram (see the screenshot under 2).
2. Some kind of visual indication about which cards are selected, like a greyer background and/or a checkmark or something (Example: http://logixsnag.com/wp-content/uploads/2016/04/Multiple-Contact-Selection-Option-SS6.jpg)

Otherwise it is looking quite good already :)

**Comment by arshbeerSingh** [comment]
@TheLastProject 

1. I think that adding the ability to select multiple cards (Issue #14 ) should have a seperate pull request as Issue #65 does not directly relate to this. And, I am willing to work on that issue as well (after fixing the current issue)

2. Yes, I think that this would be a better way to represent the selected card(s) and I will implement the same soon.

**Comment by TheLastProject** [comment]
1. I would generally prefer to keep the master branch in a "releasable state" at any time and I don't really like the in-between state without multiple selections, but seeing how fast you've been working I'm okay with your preference of doing one pull request per issue.
2. Okay :)

**Comment by TheLastProject** [comment]
Are you still interested in finishing this? Or can I help in some way?

**Comment by arshbeerSingh** [comment]
@TheLastProject I am still interested in finishing this but I was struck at exporting cards when using multi-select. I will try to fix this issue by the coming Monday

**Comment by arshbeerSingh** [comment]
May need testing before merging

**Comment by TheLastProject** [comment]
Hmm, I'm not quite sure about your last commit. I am honestly quite worried about generating such a long import URL. Given we don't know how long user notes will be and how many cards they share at once, I worry some browsers may refuse to open these URLs: https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers. It also adds a lot of complexity that I'm not sure I'm comfortable with (especially not without extensive unit tests).

I think I would much prefer the share message to just contain multiple URLs so that the code stays simpler:

1 card:
```
I want to share a card with you
https://thelastproject.github.io/Catima/share?...
```

Multiple cards:
```
I want to share 3 cards with you
https://thelastproject.github.io/Catima/share?...
https://thelastproject.github.io/Catima/share?...
https://thelastproject.github.io/Catima/share?...
```

Perhaps we could prefix the URLs with a store like such to give the URLs some meaning for end-users:

1 card:
```
I want to share a card with you from Grocery Store
https://thelastproject.github.io/Catima/share?...
```

Multiple cards:
```
I want to share 3 cards with you
Grocery Store: https://thelastproject.github.io/Catima/share?...
Fashion Store: https://thelastproject.github.io/Catima/share?...
Book Store: https://thelastproject.github.io/Catima/share?...
```

**Comment by TheLastProject** [comment]
Hey @arshbeerSingh, I still want to include this in Catima. Do you still want to work on this or should I try to fix up the last things myself? I don't mind doing it myself but I don't want to take things away from you if you want to work on it yourself.

**Comment by TheLastProject** [comment]
I'm closing this in favor of #205. Thank you for your help with this!

**Pull request closed without merging**
