### PR TITLE
Choose image as card icon

### PR DESCRIPTION
**Pull request by TheLastProject**
- [X] Set image as icon
- [x] Revert back to colour
- [x] Unit tests
- [x] Fix grey border around image
- [x] Fix icon changing while dragging on home screen
- [x] Import
- [x] Export

### CODE REVIEW

**Comment by TheLastProject** [comment]
I wish I could figure out why the hell these unit tests are failing :(

**Comment by leaumar** [comment]
Disclaimer: I'm just a java dev, my experience with android specifically is "I touched it like once", but I did get somewhere with a flutter app I eventually binned at least.

I'd like to suggest squashing and rebasing your code onto master first, since there are conflicts now in `LoyaltyCardViewActivityTest`, which are best resolved by a maintainer (they're not all obvious). Knowing you only need to account for changes in the PR and not any extra changes to unite with master makes helping more appealing. Maybe that'll already change something about the issues too.

I've been wanting a different card wallet, but not having the front photos representing each card in the UI turns me off from catima, though I like the rest of it. I gave the branch a go in the emulator and I love how your implementation just takes images, respects whatever their ratio is, and doesn't require me to awkwardly/tediously crop and center them or live with messed up aspect ratios. So I'm quite interested in this PR now.

In both tests, `activity.findViewById(R.id.thumbnail)` being null is the cause. So the rubber duck in me asks if (assuming this works that way) you have 1 and only 1 element ID'd `"thumbnail"` in the card edit activity, and if this activity is rendered and ready to go when this assertion is run. Those are the first obvious troubleshooting steps to me, you're probably way ahead of me but I gotta start from 0 here.

I'd be willing to spend some time pair-working with you (would Discord work?) if that could help you figure it out. Having 2 pairs of eyes is better than 1 pair of eyes, especially if you need to teach the other person how your changes _and_ the existing code work.

**Comment by leaumar** [comment]
Thanks. There seems to be a test timeout now?

**Comment by TheLastProject** [comment]
>I'd like to suggest squashing and rebasing your code onto master first, since there are conflicts now in LoyaltyCardViewActivityTest, which are best resolved by a maintainer (they're not all obvious). Knowing you only need to account for changes in the PR and not any extra changes to unite with master makes helping more appealing. Maybe that'll already change something about the issues too.

You caught me right after merging some other PR that caused a new conflict, so I merged master back into the branch now :)

>In both tests, activity.findViewById(R.id.thumbnail) being null is the cause. So the rubber duck in me asks if (assuming this works that way) you have 1 and only 1 element ID'd "thumbnail" in the card edit activity, and if this activity is rendered and ready to go when this assertion is run. Those are the first obvious troubleshooting steps to me, you're probably way ahead of me but I gotta start from 0 here.

There is indeed one element named "thumbnail" (because IDs have to be unique). Your rubber duck steps sound sensible. I honestly can't remember what I did or didn't try anymore, I might have skipped a very basic step due to having spent so much time in this PR. You know, the "tunnel vision" you get when you focus on something too much where you miss basic other things. So I should probably start from 0 myself again too.

>I'd be willing to spend some time pair-working with you (would Discord work?) if that could help you figure it out. Having 2 pairs of eyes is better than 1 pair of eyes, especially if you need to teach the other person how your changes and the existing code work.

I don't use Discord for code stuff normally but feel free to add me on TLP#8116 :)

>Thanks. There seems to be a test timeout now?

Wow, you're fast to notice. Not a test timeout, but sometimes the tests literally segfault Java itself. No clue why. When that happens I just tell GitHub to run the build again and generally it works then (like now). I should probably find out what goes wrong there one day but it doesn't really have much of a priority for me as the workaround is quite simple (just retry).

**Pull request merged**
