### PR TITLE
Adding notification feature

### LINKED ISSUE #410: Notification before expiry date
Catima allows setting an expiry date. It would be useful to get a notification before the card is expired, in the case of cards with monetary value.

Could be implemented by setting an per-card notification or by adding it to the settings. 
Like being able to set a notification for x weeks or days before the expiry date.

### PR DESCRIPTION
**Pull request by Ashutoshgupta22**
Hey! please review the changes.

Resolves #410

### CODE REVIEW

**Comment by Ashutoshgupta22** [comment]
Thanks! 

1.  I agree , it will be better to save the date and time in the database .But it will take some time as I have to learn more        about SQLite.

2. Yeah, I too ,thought about using this UI . but I think as a user I would save different types of cards like for shopping , restaurants and I would want to get reminders for each of them at a  time when I can use that card . For example ,
if I have to go to a restaurant on next Sunday at 8pm ,( it will be much easier to set that with a calendar and I would not have to calculate the no. of days ), I will get that notification at the perfect time , rather than getting that notification on that morning and have to keep in my mind all day. It gives more options to the users.

**Comment by TheLastProject** [comment]
2. Please replace the checkbox with an "Add reminder" button, which opens that dialog which first asks how many days in advance and then the desired time of the alert. We can then put a X to the right of the reminder to remove the reminder again. We can start with only supporting a single reminder per card, but maybe later extend it to allow multiple reminders like how Android calendar allows.

3. Agreed, 365 is a very logical maximum, let's go for that :)

**Comment by Ashutoshgupta22** [comment]
Sure , let's do that .

**Comment by TheLastProject** [comment]
I would personally strongly prefer putting the text "Reminders" on top and the "Add reminder" button on the bottom because:

1. You don't need a "No reminders added." text, it is obvious because there is nothing between the title and the button.
2. You first see all your reminders before being asked to add one, which I consider a feature, because it allows you to see "Oh, I already have a reminder for 1 week before, don't need to add another one" which would take more scrolling if the "Add reminder" button was above. It seem to me that it would be very rare to want to add an extra reminder without first seeing what reminders you currently have.

So, that would be this layout:
```
Reminders
---------
<Reminder 1> X
[Add reminder]
```

**Comment by TheLastProject** [comment]
I would remove the spacing above the "Add reminder" button but otherwise yes, perfect :)

**Pull request closed without merging**
