### PR TITLE
Adding and viewing front/back images

### LINKED ISSUE #15: Store photographs of the card
<a href="https://github.com/matthijskooijman"></img></a> **Issue by [matthijskooijman](https://github.com/matthijskooijman)**
_Monday Sep 25, 2017 at 09:37 GMT_
_Originally opened as https://github.com/brarcher/loyalty-card-locker/issues/144_

----

It would make sense to, in addition to storing the card number / bar code, store photographs of the card itself. In some cases, this helps convincing store clerks that you're actually showing a customer card. It also makes displaying a card prettier (IMHO), since there's a nice image instead of just the barcode.

Additionally, the card overview could show the card front or back instead of just the card name (this is what [mobile pocket](https://play.google.com/store/apps/details?id=at.bluesource.mobilepocket&hl=en) also does. They offer pre-fab pictures for a lot of cards, but you can also take your own photographs).

This ties in with #86 (adding a logo to a card to use in the overview) and with #136 (setting a custom color for each card in the overview).

### PR DESCRIPTION
**Pull request by TheLastProject**
- [x] Add front and back picture from file
- [ ] Unit test
- [x] Add front and back picture from camera
- [ ] Unit test
- [x] Remove front and back picture from card
- [ ] Unit test
- [x] View front and back picture
- [ ] Unit test
- [x] Fullscreen front or back picture
- [ ] Unit test
- [x] Export front and back picture to Catima backup
- [x] Unit test
- [x] Import front and back picture from Catima backup
- [x] Unit test
- [ ] Import front and back picture from Fidme backup
- [ ] Unit test
- [x] Delete images on deleting card
- [ ] Unit test
- [ ] Stupid spacing bug (https://github.com/TheLastProject/Catima/pull/215#issuecomment-834871373)

Closes #15.

### CODE REVIEW

**Comment by TheLastProject** [comment]
Screenshot_20210508-014611_Catima_Debug

Accidentally introduced a rather annoying spacing bug (above the extra data button) in this branch...

**Comment by TheLastProject** [comment]
I think I want to put a hash of the image in the front and back image DB table and load the image from that hash on the filesystem. That way we can also deal with duplicates nicely.

**Comment by TheLastProject** [comment]
Deduplication makes no sense as there is no reason for an user to use the exact same card twice. Probably just Boolean DB fields on if there is an image and saving it in subdirectories per card ID and then exporting like that in a .zip together with the current .csv

**Comment by ILoveFOSS** [comment]
If help testing the feature is required, I can help out with a Samsung A6 (Android 10/One-UI 2.0) & Xiaomi Note 4 (Android 7/MIUI 11).

As well, would you maybe consider separating "Import front and back picture from Fidme backup" and create an extra feature "Import from Fidme" to implement on a later stage? Just like https://github.com/TheLastProject/Catima/issues/223 . As it seems to me, this one is blocking release of the general capability of picture import? In a first step, Fidme users could then import pictures of their required cards by taking a photo of them too.

**Comment by TheLastProject** [comment]
The problem isn't so much testing, it's more that actual data storage under Android is new to me and Android keeps making so many changes to data storage that the risks of possibly getting it wrong worry me a lot.

Importing from Fidme is already supported, but yeah, importing images from a backup does need this feature.

**Comment by TheLastProject** [comment]
I'm starting to feel pretty positive about this code, but I'm still having some trouble getting it to be more unit-testable. So if someone is good with unit tests I could use help there, that's like... the final stretch for this feature I guess :)

**Comment by TheLastProject** [comment]
Oh, and the stupid spacing bug I mentioned in https://github.com/TheLastProject/Catima/pull/215#issuecomment-834871373... I forgot about that one...

**Comment by TheLastProject** [comment]
Ehhh, you know what, it's good enough

**Pull request merged**
